version: '3.8'

services:
  api:
    build: 
      context: ./api
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./api:/app
    networks:
      - my_network

  image_processer:
    build: 
      context: ./image_processer
    ports:
      - 3002:3002
    working_dir: /app
    volumes:
      - ./image_processer:/app
    networks:
      - my_network

networks:
  my_network:
